steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_IMAGE}"
      - "-f"
      - "${_DOCKERFILE}"
      - "."

images:
  - "${_IMAGE}"

substitutions:
  _IMAGE: "gcr.io/media-circle/redis-search-api"
  _DOCKERFILE: "src/search_api/Dockerfile"
