"""
Podcast Core Service - Base service with core utilities.
Provides foundation for search and discovery operations.
"""

from typing import Any

from api.podcast.auth import Auth
from api.podcast.models import MCEpisodeItem, MCPodcastItem
from utils.get_logger import get_logger
from utils.redis_cache import RedisCache

# Cache configuration - 1 hour for podcast data
CacheExpiration = 60 * 60  # 1 hour
PodcastCache = RedisCache(
    defaultTTL=CacheExpiration,
    prefix="podcast",
    verbose=False,
    isClassMethod=True,
)
PodcastFunctionCache = RedisCache(
    defaultTTL=60 * 60,  # 1 hour
    prefix="podcast_func",
    verbose=False,
    isClassMethod=False,
)
logger = get_logger(__name__)


class PodcastService(Auth):
    """
    Base Podcast service with core utilities.
    Provides foundation for search and discovery operations.
    """

    def _safe_episode_count(self, episode_count: Any) -> int:
        """
        Safely convert episode_count to a non-negative integer.

        Args:
            episode_count: Episode count value (may be None, string, or int)

        Returns:
            Non-negative integer episode count, or 0 if invalid
        """
        try:
            if episode_count is not None:
                count = int(episode_count)
                return max(0, count)
            return 0
        except (ValueError, TypeError):
            return 0

    def _has_valid_image(self, podcast_data: dict | MCPodcastItem) -> bool:
        """
        Check if podcast has a valid image URL.

        Args:
            podcast_data: Processed podcast dictionary or MCPodcastItem object

        Returns:
            True if podcast has a valid image URL, False otherwise
        """
        # Check both image and artwork fields
        if isinstance(podcast_data, MCPodcastItem):
            image_url = podcast_data.image
            artwork_url = podcast_data.artwork
        else:
            image_url = podcast_data.get("image")
            artwork_url = podcast_data.get("artwork")

        # A podcast has a valid image if either field contains a non-empty URL
        # that starts with http:// or https://
        def is_valid_url(url: Any) -> bool:
            if not url or not isinstance(url, str):
                return False
            url = url.strip()
            return url.startswith(("http://", "https://")) and len(url) > 10

        return bool(is_valid_url(image_url) or is_valid_url(artwork_url))

    def _process_podcast_item(self, podcast_data: dict[str, Any]) -> MCPodcastItem:
        """
        Process and normalize a podcast item from PodcastIndex.

        Args:
            podcast_data: Raw podcast data from PodcastIndex API

        Returns:
            MCPodcastItem with standardized fields and auto-generated mc_id/mc_type
        """
        podcast_id = podcast_data.get("id")
        result_dict = {
            "id": podcast_id,
            "title": podcast_data.get("title", ""),
            "url": podcast_data.get("url", ""),
            "site": podcast_data.get("site"),
            "description": podcast_data.get("description"),
            "author": podcast_data.get("author"),
            "owner_name": podcast_data.get("owner_name"),
            "image": podcast_data.get("image"),
            "artwork": podcast_data.get("artwork"),
            "last_update_time": podcast_data.get("last_update_time"),
            "trend_score": podcast_data.get("trend_score"),
            "language": podcast_data.get("language"),
            "categories": podcast_data.get("categories", {}),
            "episode_count": podcast_data.get("episode_count", 0),
            "itunes_id": podcast_data.get("itunes_id"),
            "spotify_url": podcast_data.get("spotify_url"),
            "podcast_guid": podcast_data.get("podcast_guid"),
            "relevancy_score": podcast_data.get("relevancy_score"),
            "source_id": str(podcast_id) if podcast_id is not None else None,
        }
        # mc_id and mc_type are automatically generated by the MCPodcastItem model validator
        return MCPodcastItem.model_validate(result_dict)

    def _process_episode_item(self, episode_data: dict[str, Any]) -> MCEpisodeItem:
        """
        Process and normalize an episode item from PodcastIndex.

        Args:
            episode_data: Raw episode data from PodcastIndex API

        Returns:
            MCEpisodeItem with standardized fields and auto-generated mc_id/mc_type
        """
        episode_id = episode_data.get("id")
        result_dict = {
            "id": episode_id,
            "title": episode_data.get("title", ""),
            "description": episode_data.get("description"),
            "link": episode_data.get("link"),
            "guid": episode_data.get("guid"),
            "date_published": episode_data.get("date_published"),
            "enclosure_url": episode_data.get("enclosure_url"),  # This is the playback URL
            "enclosure_type": episode_data.get("enclosure_type"),
            "enclosure_length": episode_data.get("enclosure_length"),
            "duration_seconds": episode_data.get("duration_seconds"),
            "explicit": episode_data.get("explicit"),
            "episode_type": episode_data.get("episode_type"),
            "season": episode_data.get("season"),
            "episode": episode_data.get("episode"),
            "feed_id": episode_data.get("feed_id"),
            "feed_title": episode_data.get("feed_title"),
            "image": episode_data.get("image"),
            "source_id": str(episode_id) if episode_id is not None else None,
        }
        # mc_id and mc_type are automatically generated by the MCEpisodeItem model validator
        return MCEpisodeItem.model_validate(result_dict)


def redis_doc_to_mc_podcast_item(doc: dict[str, Any]) -> MCPodcastItem:
    """Convert a Redis ``idx:podcasts`` JSON document to an ``MCPodcastItem``.

    The Redis document stores the namespaced ``mc_id`` (e.g.
    ``podcastindex_podcast_920666``) in the ``id`` field while the integer
    PodcastIndex feed id lives in ``source_id``. ``MCPodcastItem.id`` is the
    integer feed id, so we coerce ``source_id`` accordingly.

    ``categories`` may be stored as either a dict (legacy bulk loader) or a
    list of normalized strings (nightly ETL). ``MCPodcastItem.categories``
    expects a dict, so a list is converted to a positional dict.
    """
    raw_source_id = doc.get("source_id")
    feed_id = 0
    if raw_source_id is not None:
        try:
            feed_id = int(raw_source_id)
        except (TypeError, ValueError):
            feed_id = 0

    categories_raw = doc.get("categories")
    categories: dict[str, Any]
    if isinstance(categories_raw, dict):
        categories = categories_raw
    elif isinstance(categories_raw, list):
        categories = {str(i): v for i, v in enumerate(categories_raw, start=1)}
    else:
        categories = {}

    payload: dict[str, Any] = {
        "id": feed_id,
        "title": doc.get("title") or doc.get("search_title") or "",
        "url": doc.get("url") or "",
        "site": doc.get("site"),
        "description": doc.get("description") or doc.get("overview"),
        "author": doc.get("author"),
        "owner_name": doc.get("owner_name"),
        "image": doc.get("image"),
        "artwork": doc.get("artwork"),
        "last_update_time": doc.get("last_update_time"),
        "trend_score": doc.get("trend_score"),
        "relevancy_score": doc.get("relevancy_score"),
        "language": doc.get("language"),
        "categories": categories,
        "episode_count": doc.get("episode_count") or 0,
        "itunes_id": doc.get("itunes_id"),
        "podcast_guid": doc.get("podcast_guid"),
        "spotify_url": doc.get("spotify_url"),
        "source_id": str(feed_id) if feed_id else None,
    }
    return MCPodcastItem.model_validate(payload)
